### ISSUE TITLE
Index holders of staked + unstaked tokens

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-subgraph#1]
Projects would benefit from a means of seeing all holders of their treasury token—both staked and unstaked (ERC20). We can already display holders of staked tokens, but currently there's no way to reliably show balances of unstaked ERC20 tokens.

**Need to solve:** index `transfer()` events for a project's ERC20 token.

**Comment by Data-Nexus** [comment]
Utilizing a factory could resolve this. The Graph utilizes this as a solution for tracking curation shares with each new subgraph posted. As signal is added, it actually creates an ERC20 token for that subgraph, this is dynamically tracked for each subgraph.

**Comment by peripheralist** [comment]
> Utilizing a factory could resolve this. The Graph utilizes this as a solution for tracking curation shares with each new subgraph posted. As signal is added, it actually creates an ERC20 token for that subgraph, this is dynamically tracked for each subgraph.

this is the plan! it hasn't been done yet because the v1 contracts don't emit the address of the ERC20 tokens. Once this is added in v2 (not v1.1) we'll move to a factory pattern.
