### ISSUE TITLE
Update current Subgraph for V1.1

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-subgraph#10]
This is open ended, and will continue to be adapted here or into other issues as needed.

The goal will be to support (at a minimum) feature parity with the current Juicebox app using subgraph v1.0.0.

Newly introduced patterns will be:
- Deprecating the need to manually track project ERC20 tokens by relying on subgraph [data source templating](https://thegraph.com/docs/developer/create-subgraph-hosted#data-source-templates)

**Comment by Data-Nexus** [comment]
Will projects that have launched on v1 be able to migrate to the v2 contract? 

We may be able to co-mingle v1 and v2 entities but this would need to be well thought through (ensuring fields are nullable and have proper void handlings for v2 features that weren't available on v1).

The safest route is having v2 deployed separately but both routes are possible. But you'll also want to consider how to route the query API's when a project is running v1 vs v2 if they're both fed into the same UI.

**Comment by peripheralist** [comment]
Editing this issue to be for v1.1 instead of v2
