### ISSUE TITLE
Index balance of owner wallet

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-subgraph#2]
Some projects (SharkDAO) have their owner wallet balance displayed with the "paid" bar. However, the timeline graph only reflects the JB contract balance read from the `Project` subgraph entity's `currentBalance` property.

If we could also index the owner's wallet balance, it could be included in the project balance timeline.

**Comment by Data-Nexus** [comment]
Can you explain this issue a bit further? 

If I'm understanding correctly, we want to add an 'owners balance' of their token to the project's entitiy? If so, we would need to utilize a factory contract that would start listening to transfer events and update the sum on every transfer in/out for the project owner.
